export const BANNERS = [
  { img: 'https://jiliwin.9terawolf.com/cms/banner/image/bd-desktop-69c9f62e73810.jpg', tag: 'Welcome Bonus', title: 'Get 100% up to $500', cta: 'Claim Bonus' },
  { img: 'https://jiliwin.9terawolf.com/cms/banner/image/bd-desktop-69c115dc90557.jpg', tag: 'Aviator', title: 'Fly High & Win Big', cta: 'Play Now' },
  { img: 'https://jiliwin.9terawolf.com/cms/banner/image/bd-desktop-689c462a80042.jpg', tag: 'Tournaments', title: 'Daily Prize Pools', cta: 'Join Now' },
];

// Extended game images array with all provided URLs
export const GAME_IMAGES = [
  'https://xxxbetgames.com/image/vertical_2/30200.webp',
  'https://xxxbetgames.com/image/vertical_2/53432.webp',
  'https://xxxbetgames.com/image/vertical_2/20947.webp',
  'https://xxxbetgames.com/image/vertical_2/41180.webp',
  'https://xxxbetgames.com/image/vertical_2/63636.webp',
  'https://xxxbetgames.com/image/vertical_2/53086.webp',
  'https://xxxbetgames.com/image/vertical_2/38792.webp',
  'https://xxxbetgames.com/image/vertical_2/64059.webp',
  'https://xxxbetgames.com/image/vertical_2/56396.webp',
  'https://xxxbetgames.com/image/vertical_2/14155.webp',
  'https://xxxbetgames.com/image/vertical_2/4351.webp',
  'https://xxxbetgames.com/image/vertical_2/13860.webp',
  'https://xxxbetgames.com/image/vertical_2/30278.webp',
  'https://xxxbetgames.com/image/vertical_2/64060.webp',
  'https://xxxbetgames.com/image/vertical_2/62554.webp',
  'https://xxxbetgames.com/image/vertical_2/62996.webp',
  'https://xxxbetgames.com/image/vertical_2/15754.webp',
  'https://xxxbetgames.com/image/vertical_2/28.webp',
  'https://xxxbetgames.com/image/vertical_2/11657.webp',
  'https://xxxbetgames.com/image/vertical_2/26067.webp',
  'https://xxxbetgames.com/image/vertical_2/58090.webp',
  'https://xxxbetgames.com/image/vertical_2/54270.webp',
  'https://xxxbetgames.com/image/vertical_2/53621.webp',
  'https://xxxbetgames.com/image/vertical_2/25872.webp',
  'https://xxxbetgames.com/image/vertical_2/50314.webp',
  'https://xxxbetgames.com/image/vertical_2/7445.webp',
  'https://xxxbetgames.com/image/vertical_2/63637.webp',
  'https://xxxbetgames.com/image/vertical_2/61432.webp',
  'https://xxxbetgames.com/image/vertical_2/50257.webp',
  // New images
  'https://xxxbetgames.com/image/vertical_2/63246.webp',
  'https://xxxbetgames.com/image/vertical_2/63079.webp',
  'https://xxxbetgames.com/image/vertical_2/63201.webp',
  'https://xxxbetgames.com/image/vertical_2/64203.webp',
  'https://xxxbetgames.com/image/vertical_2/63296.webp',
  'https://xxxbetgames.com/image/vertical_2/63321.webp',
  'https://xxxbetgames.com/image/vertical_2/42940.webp',
  'https://xxxbetgames.com/image/vertical_2/26594.webp',
  'https://xxxbetgames.com/image/vertical_2/14241.webp',
  'https://xxxbetgames.com/image/vertical_2/50316.webp',
  'https://xxxbetgames.com/image/vertical_2/26277.webp',
  'https://xxxbetgames.com/image/vertical_2/59248.webp',
];

// Extended ALL_GAMES with more games using new images
export const ALL_GAMES = [
  { name: 'Starburst', provider: 'NetEnt', img: GAME_IMAGES[0], badge: 'hot', plays: '124K' },
  { name: 'Book of Dead', provider: "Play'n GO", img: GAME_IMAGES[1], badge: '', plays: '98K' },
  { name: 'Mega Moolah', provider: 'Microgaming', img: GAME_IMAGES[2], badge: 'jackpot', plays: '245K' },
  { name: 'Crash X', provider: 'Spribe', img: GAME_IMAGES[3], badge: 'hot', plays: '167K' },
  { name: "Gonzo's Quest", provider: 'NetEnt', img: GAME_IMAGES[4], badge: '', plays: '112K' },
  { name: 'Sweet Bonanza', provider: 'Pragmatic', img: GAME_IMAGES[5], badge: 'new', plays: '89K' },
  { name: 'Lightning Roulette', provider: 'Evolution', img: GAME_IMAGES[6], badge: 'hot', plays: '78K' },
  { name: 'Bonus Hunter', provider: 'Hacksaw', img: GAME_IMAGES[7], badge: '', plays: '92K' },
  { name: 'Fast Cash', provider: 'Hacksaw', img: GAME_IMAGES[8], badge: 'new', plays: '156K' },
  { name: 'Dragon Kingdom', provider: 'Pragmatic', img: GAME_IMAGES[10], badge: '', plays: '67K' },
  { name: 'Fish Hunter', provider: 'Spadegaming', img: GAME_IMAGES[11], badge: '', plays: '78K' },

  { name: 'Dead or Alive 2', provider: 'NetEnt', img: GAME_IMAGES[13], badge: '', plays: '87K' },
  { name: 'Big Bass Bonanza', provider: 'Pragmatic', img: GAME_IMAGES[14], badge: 'new', plays: '112K' },
  { name: 'The Dog House', provider: 'Pragmatic', img: GAME_IMAGES[15], badge: '', plays: '76K' },
  { name: 'Reactoonz', provider: "Play'n GO", img: GAME_IMAGES[16], badge: 'hot', plays: '143K' },
  { name: 'Viking Clash', provider: 'Microgaming', img: GAME_IMAGES[17], badge: '', plays: '54K' },
  { name: 'Temple Tumble', provider: 'Relax Gaming', img: GAME_IMAGES[18], badge: 'new', plays: '91K' },
  { name: 'Money Train 2', provider: 'Relax Gaming', img: GAME_IMAGES[19], badge: 'hot', plays: '178K' },
  { name: 'Jammin Jars', provider: 'Push Gaming', img: GAME_IMAGES[20], badge: '', plays: '105K' },
  { name: 'Fat Rabbit', provider: 'Push Gaming', img: GAME_IMAGES[21], badge: '', plays: '62K' },
  { name: 'Razor Shark', provider: 'Push Gaming', img: GAME_IMAGES[22], badge: 'hot', plays: '198K' },
  { name: 'Wild West Gold', provider: 'Pragmatic', img: GAME_IMAGES[23], badge: 'new', plays: '83K' },
  { name: 'Gates of Olympus', provider: 'Pragmatic', img: GAME_IMAGES[24], badge: 'hot', plays: '267K' },
  { name: 'Starlight Princess', provider: 'Pragmatic', img: GAME_IMAGES[25], badge: 'new', plays: '134K' },
  { name: 'Sugar Rush', provider: 'Pragmatic', img: GAME_IMAGES[26], badge: 'hot', plays: '156K' },
  { name: 'Spaceman', provider: 'Pragmatic', img: GAME_IMAGES[27], badge: '', plays: '72K' },
  { name: 'Mystic Chief', provider: 'Pragmatic', img: GAME_IMAGES[28], badge: '', plays: '45K' },
    { name: 'Starburst', provider: 'NetEnt', img: GAME_IMAGES[0], badge: 'hot', plays: '124K' },
  { name: 'Book of Dead', provider: "Play'n GO", img: GAME_IMAGES[1], badge: '', plays: '98K' },
  { name: 'Mega Moolah', provider: 'Microgaming', img: GAME_IMAGES[2], badge: 'jackpot', plays: '245K' },
  { name: 'Crash X', provider: 'Spribe', img: GAME_IMAGES[3], badge: 'hot', plays: '167K' },
  { name: "Gonzo's Quest", provider: 'NetEnt', img: GAME_IMAGES[4], badge: '', plays: '112K' },
  { name: 'Sweet Bonanza', provider: 'Pragmatic', img: GAME_IMAGES[5], badge: 'new', plays: '89K' },
  { name: 'Lightning Roulette', provider: 'Evolution', img: GAME_IMAGES[6], badge: 'hot', plays: '78K' },
  { name: 'Bonus Hunter', provider: 'Hacksaw', img: GAME_IMAGES[7], badge: '', plays: '92K' },
  { name: 'Fast Cash', provider: 'Hacksaw', img: GAME_IMAGES[8], badge: 'new', plays: '156K' },
  { name: 'Megaways Jackpot', provider: 'Big Time Gaming', img: GAME_IMAGES[9], badge: 'jackpot', plays: '145K' },
  { name: 'Dragon Kingdom', provider: 'Pragmatic', img: GAME_IMAGES[10], badge: '', plays: '67K' },
  { name: 'Fish Hunter', provider: 'Spadegaming', img: GAME_IMAGES[11], badge: '', plays: '78K' },
  // New Games
  { name: 'Aztec Gold', provider: 'Pragmatic', img: GAME_IMAGES[29], badge: 'hot', plays: '189K' },
  { name: 'Diamond Strike', provider: 'Pragmatic', img: GAME_IMAGES[30], badge: '', plays: '73K' },
  { name: 'Wild Walker', provider: 'NetEnt', img: GAME_IMAGES[31], badge: 'new', plays: '56K' },
  { name: 'Vampire Vixen', provider: 'Microgaming', img: GAME_IMAGES[32], badge: '', plays: '68K' },
  { name: 'Treasure Nile', provider: 'Microgaming', img: GAME_IMAGES[33], badge: 'jackpot', plays: '212K' },
  { name: 'Lucky Lady', provider: 'Playtech', img: GAME_IMAGES[34], badge: '', plays: '94K' },
  { name: 'Fire Strike', provider: 'Pragmatic', img: GAME_IMAGES[35], badge: 'hot', plays: '177K' },
  { name: 'Mustang Gold', provider: 'Pragmatic', img: GAME_IMAGES[36], badge: '', plays: '88K' },
  { name: 'Chilli Heat', provider: 'Pragmatic', img: GAME_IMAGES[37], badge: 'new', plays: '103K' },
  { name: 'Great Rhino', provider: 'Pragmatic', img: GAME_IMAGES[38], badge: '', plays: '79K' },
  { name: 'Pyramid King', provider: 'Pragmatic', img: GAME_IMAGES[39], badge: 'hot', plays: '146K' },
  { name: 'Crystal Caverns', provider: 'NetEnt', img: GAME_IMAGES[40], badge: 'new', plays: '61K' },
  { name: 'Phantom Thief', provider: 'Hacksaw', img: GAME_IMAGES[29], badge: '', plays: '52K' },
  { name: 'Mystic Egypt', provider: 'Playtech', img: GAME_IMAGES[30], badge: 'hot', plays: '128K' },
  { name: 'Dragon Pearls', provider: 'Pragmatic', img: GAME_IMAGES[31], badge: '', plays: '95K' },
  { name: 'Honey Honey', provider: 'Pragmatic', img: GAME_IMAGES[32], badge: '', plays: '47K' },
  { name: 'Santa Megaways', provider: 'Big Time Gaming', img: GAME_IMAGES[33], badge: 'jackpot', plays: '234K' },
  { name: 'Buffalo King', provider: 'Pragmatic', img: GAME_IMAGES[34], badge: 'hot', plays: '198K' },
  { name: 'Madame Destiny', provider: 'Pragmatic', img: GAME_IMAGES[35], badge: '', plays: '82K' },
  { name: 'Jungle Gorilla', provider: 'Pragmatic', img: GAME_IMAGES[36], badge: 'new', plays: '71K' },
  { name: 'Coin Volcano', provider: 'Spribe', img: GAME_IMAGES[37], badge: 'hot', plays: '165K' },
  { name: 'Space Wars', provider: 'NetEnt', img: GAME_IMAGES[38], badge: '', plays: '59K' },
    { name: 'Lucky Lady', provider: 'Playtech', img: GAME_IMAGES[34], badge: '', plays: '94K' },
  { name: 'Fire Strike', provider: 'Pragmatic', img: GAME_IMAGES[35], badge: 'hot', plays: '177K' },
  { name: 'Mustang Gold', provider: 'Pragmatic', img: GAME_IMAGES[36], badge: '', plays: '88K' },
  { name: 'Chilli Heat', provider: 'Pragmatic', img: GAME_IMAGES[37], badge: 'new', plays: '103K' },
  { name: 'Great Rhino', provider: 'Pragmatic', img: GAME_IMAGES[38], badge: '', plays: '79K' },
  { name: 'Pyramid King', provider: 'Pragmatic', img: GAME_IMAGES[39], badge: 'hot', plays: '146K' },
  { name: 'Crystal Caverns', provider: 'NetEnt', img: GAME_IMAGES[40], badge: 'new', plays: '61K' },
  { name: 'Phantom Thief', provider: 'Hacksaw', img: GAME_IMAGES[29], badge: '', plays: '52K' },
  { name: 'Finn and the Swirly Spin', provider: 'NetEnt', img: GAME_IMAGES[40], badge: 'new', plays: '104K' },
  { name: 'Mustang Gold', provider: 'Pragmatic', img: GAME_IMAGES[36], badge: '', plays: '88K' },
  { name: 'Mystic Chief', provider: 'Pragmatic', img: GAME_IMAGES[28], badge: '', plays: '45K' },
  
];

export const TOP_NAV_H = [
  { id: 'CASINO', label: 'Casino', type: 'text' },
  { id: 'MEGABLOCK', label: 'Megablock', type: 'megablock' },
  { id: 'TOURNAMENTS', label: 'Tournaments', type: 'text' },
  { id: 'GLORY_GAMES', label: 'Glory Games', type: 'text' },
  { id: 'AVIATOR', label: 'Aviator', type: 'aviator' },
  { id: 'SPORT', label: 'Sport', type: 'text' },
];

export const MEGA_LETTERS = [
  { ch: 'M', c: '#ef4444' }, { ch: 'E', c: '#f97316' }, { ch: 'G', c: '#facc15' },
  { ch: 'A', c: '#22c55e' }, { ch: 'B', c: '#3b82f6' }, { ch: 'L', c: '#a855f7' },
  { ch: 'O', c: '#ec4899' }, { ch: 'C', c: '#06b6d4' }, { ch: 'K', c: '#ef4444' },
];

export const SB_TOP = [
  { id: 'Lobby', emoji: '👑', label: 'Lobby' },
  { id: 'Sport', emoji: '⚽', label: 'Sport' },
];

// Extended SB_CATS with more categories
export const SB_CATS = [
  { id: 'Top Games', emoji: '🏆', label: 'Top Games' },
  { id: 'Game Shows', emoji: '💰', label: 'Game Shows' },
  { id: 'Slots', emoji: '🎰', label: 'Slots' },
  { id: 'New', emoji: '🆕', label: 'New' },
  { id: 'Crash Games', emoji: '🚀', label: 'Crash Games' },
  { id: 'Cross & Win', emoji: '🎯', label: 'Cross & Win' },
  { id: 'Bonus Buy', emoji: '🎁', label: 'Bonus Buy' },
  { id: 'Live Games', emoji: '🎭', label: 'Live Games' },
  { id: 'Roulette', emoji: '🎡', label: 'Roulette' },
  { id: 'Ancient World', emoji: '🗿', label: 'Ancient World' },
  { id: 'Fast Games', emoji: '⚡', label: 'Fast Games' },
  { id: 'Fishing', emoji: '🎣', label: 'Fishing' },
  { id: 'Blackjack', emoji: '♠️', label: 'Blackjack' },
  { id: 'Megaways', emoji: '🌟', label: 'Megaways' },
  { id: 'Jackpots', emoji: '💎', label: 'Jackpots' },
  { id: 'Table Games', emoji: '🃏', label: 'Table Games' },
  { id: 'Video Poker', emoji: '🀄', label: 'Video Poker' },
  { id: 'Bingo', emoji: '🎲', label: 'Bingo' },
  { id: 'Scratch Cards', emoji: '🎫', label: 'Scratch Cards' },
  { id: 'Virtual Sports', emoji: '🏟️', label: 'Virtual Sports' },
  { id: 'Exclusive', emoji: '⭐', label: 'Exclusive' },
  { id: 'Trending', emoji: '📈', label: 'Trending' },
];

// Extended PILL_CATS with more categories for the top pills
export const PILL_CATS = [
  { id: 'Top Games', emoji: '🏆', label: 'Top Games' },
  { id: 'New', emoji: '🆕', label: 'New' },
  { id: 'Slots', emoji: '🎰', label: 'Slots' },
  { id: 'Crash Games', emoji: '🚀', label: 'Crash Games' },
  { id: 'Live Games', emoji: '🎭', label: 'Live Games' },
  { id: 'Jackpots', emoji: '💎', label: 'Jackpots' },
  { id: 'Megaways', emoji: '🌟', label: 'Megaways' },
  { id: 'Trending', emoji: '📈', label: 'Trending' },
  { id: 'Bonus Buy', emoji: '🎁', label: 'Bonus Buy' },
  { id: 'Table Games', emoji: '🃏', label: 'Table Games' },
  { id: 'Fishing', emoji: '🎣', label: 'Fishing' },
];

// Extended PROVIDERS with more game providers
export const PROVIDERS = [
  'All', 
  'NetEnt', 
  "Play'n GO", 
  'Microgaming', 
  'Evolution', 
  'Pragmatic', 
  'Spribe', 
  'Hacksaw',
  'Big Time Gaming',
  'Spadegaming',
  'Relax Gaming',
  'Push Gaming',
  'Yggdrasil',
  'Quickspin',
  'Thunderkick',
  'Red Tiger',
  'Blueprint Gaming',
  'Playtech',
];